// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/consumer/consumer.proto

package consumer

import (
	_struct "github.com/golang/protobuf/ptypes/struct"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Error severity
type ErrorInfo_Severity int32

const (
	ErrorInfo_UNKNOWN ErrorInfo_Severity = 0
	ErrorInfo_FATAL   ErrorInfo_Severity = 1
	ErrorInfo_ERROR   ErrorInfo_Severity = 2
	ErrorInfo_WARNING ErrorInfo_Severity = 3
	ErrorInfo_INFO    ErrorInfo_Severity = 4
)

// Enum value maps for ErrorInfo_Severity.
var (
	ErrorInfo_Severity_name = map[int32]string{
		0: "UNKNOWN",
		1: "FATAL",
		2: "ERROR",
		3: "WARNING",
		4: "INFO",
	}
	ErrorInfo_Severity_value = map[string]int32{
		"UNKNOWN": 0,
		"FATAL":   1,
		"ERROR":   2,
		"WARNING": 3,
		"INFO":    4,
	}
)

func (x ErrorInfo_Severity) Enum() *ErrorInfo_Severity {
	p := new(ErrorInfo_Severity)
	*p = x
	return p
}

func (x ErrorInfo_Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorInfo_Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_consumer_consumer_proto_enumTypes[0].Descriptor()
}

func (ErrorInfo_Severity) Type() protoreflect.EnumType {
	return &file_proto_consumer_consumer_proto_enumTypes[0]
}

func (x ErrorInfo_Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorInfo_Severity.Descriptor instead.
func (ErrorInfo_Severity) EnumDescriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{3, 0}
}

// Optional validation mode
type ConfigureRequest_ValidationMode int32

const (
	ConfigureRequest_VALIDATE_AND_APPLY ConfigureRequest_ValidationMode = 0
	ConfigureRequest_VALIDATE_ONLY      ConfigureRequest_ValidationMode = 1
)

// Enum value maps for ConfigureRequest_ValidationMode.
var (
	ConfigureRequest_ValidationMode_name = map[int32]string{
		0: "VALIDATE_AND_APPLY",
		1: "VALIDATE_ONLY",
	}
	ConfigureRequest_ValidationMode_value = map[string]int32{
		"VALIDATE_AND_APPLY": 0,
		"VALIDATE_ONLY":      1,
	}
)

func (x ConfigureRequest_ValidationMode) Enum() *ConfigureRequest_ValidationMode {
	p := new(ConfigureRequest_ValidationMode)
	*p = x
	return p
}

func (x ConfigureRequest_ValidationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigureRequest_ValidationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_consumer_consumer_proto_enumTypes[1].Descriptor()
}

func (ConfigureRequest_ValidationMode) Type() protoreflect.EnumType {
	return &file_proto_consumer_consumer_proto_enumTypes[1]
}

func (x ConfigureRequest_ValidationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigureRequest_ValidationMode.Descriptor instead.
func (ConfigureRequest_ValidationMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{10, 0}
}

type ValidationIssue_Severity int32

const (
	ValidationIssue_ERROR   ValidationIssue_Severity = 0
	ValidationIssue_WARNING ValidationIssue_Severity = 1
	ValidationIssue_INFO    ValidationIssue_Severity = 2
)

// Enum value maps for ValidationIssue_Severity.
var (
	ValidationIssue_Severity_name = map[int32]string{
		0: "ERROR",
		1: "WARNING",
		2: "INFO",
	}
	ValidationIssue_Severity_value = map[string]int32{
		"ERROR":   0,
		"WARNING": 1,
		"INFO":    2,
	}
)

func (x ValidationIssue_Severity) Enum() *ValidationIssue_Severity {
	p := new(ValidationIssue_Severity)
	*p = x
	return p
}

func (x ValidationIssue_Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidationIssue_Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_consumer_consumer_proto_enumTypes[2].Descriptor()
}

func (ValidationIssue_Severity) Type() protoreflect.EnumType {
	return &file_proto_consumer_consumer_proto_enumTypes[2]
}

func (x ValidationIssue_Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidationIssue_Severity.Descriptor instead.
func (ValidationIssue_Severity) EnumDescriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{12, 0}
}

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN         HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING         HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING     HealthCheckResponse_ServingStatus = 2
	HealthCheckResponse_SERVICE_UNKNOWN HealthCheckResponse_ServingStatus = 3
	HealthCheckResponse_STARTING        HealthCheckResponse_ServingStatus = 4
	HealthCheckResponse_STOPPING        HealthCheckResponse_ServingStatus = 5
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
		3: "SERVICE_UNKNOWN",
		4: "STARTING",
		5: "STOPPING",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":         0,
		"SERVING":         1,
		"NOT_SERVING":     2,
		"SERVICE_UNKNOWN": 3,
		"STARTING":        4,
		"STOPPING":        5,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_consumer_consumer_proto_enumTypes[3].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_proto_consumer_consumer_proto_enumTypes[3]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{14, 0}
}

type LifecycleRequest_Operation int32

const (
	LifecycleRequest_INITIALIZE LifecycleRequest_Operation = 0
	LifecycleRequest_SHUTDOWN   LifecycleRequest_Operation = 1
	LifecycleRequest_PAUSE      LifecycleRequest_Operation = 2
	LifecycleRequest_RESUME     LifecycleRequest_Operation = 3
	LifecycleRequest_RESET      LifecycleRequest_Operation = 4
)

// Enum value maps for LifecycleRequest_Operation.
var (
	LifecycleRequest_Operation_name = map[int32]string{
		0: "INITIALIZE",
		1: "SHUTDOWN",
		2: "PAUSE",
		3: "RESUME",
		4: "RESET",
	}
	LifecycleRequest_Operation_value = map[string]int32{
		"INITIALIZE": 0,
		"SHUTDOWN":   1,
		"PAUSE":      2,
		"RESUME":     3,
		"RESET":      4,
	}
)

func (x LifecycleRequest_Operation) Enum() *LifecycleRequest_Operation {
	p := new(LifecycleRequest_Operation)
	*p = x
	return p
}

func (x LifecycleRequest_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LifecycleRequest_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_consumer_consumer_proto_enumTypes[4].Descriptor()
}

func (LifecycleRequest_Operation) Type() protoreflect.EnumType {
	return &file_proto_consumer_consumer_proto_enumTypes[4]
}

func (x LifecycleRequest_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LifecycleRequest_Operation.Descriptor instead.
func (LifecycleRequest_Operation) EnumDescriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{18, 0}
}

// DataMessage represents the basic message that the consumer will receive.
type DataMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The raw data payload.
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// Enhanced metadata with support for complex values.
	Metadata *_struct.Struct `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Timestamp when the message was created.
	Timestamp *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Content type of the payload (e.g., "application/json", "stellar/xdr")
	ContentType string `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// Unique message identifier
	MessageId     string `protobuf:"bytes,5,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataMessage) Reset() {
	*x = DataMessage{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataMessage) ProtoMessage() {}

func (x *DataMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataMessage.ProtoReflect.Descriptor instead.
func (*DataMessage) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{0}
}

func (x *DataMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DataMessage) GetMetadata() *_struct.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DataMessage) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DataMessage) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *DataMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

// ConsumeRequest wraps a DataMessage to be consumed.
type ConsumeRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Message *DataMessage           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Optional request ID for correlation
	RequestId     string `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{1}
}

func (x *ConsumeRequest) GetMessage() *DataMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ConsumeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// ConsumeResponse acknowledges the consumption of a message.
type ConsumeResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Success      bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Detailed error information
	ErrorInfo *ErrorInfo `protobuf:"bytes,3,opt,name=error_info,json=errorInfo,proto3" json:"error_info,omitempty"`
	// Response correlation ID matching the request
	RequestId     string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeResponse) Reset() {
	*x = ConsumeResponse{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeResponse) ProtoMessage() {}

func (x *ConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeResponse.ProtoReflect.Descriptor instead.
func (*ConsumeResponse) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{2}
}

func (x *ConsumeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConsumeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ConsumeResponse) GetErrorInfo() *ErrorInfo {
	if x != nil {
		return x.ErrorInfo
	}
	return nil
}

func (x *ConsumeResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Error information for detailed reporting
type ErrorInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error type (e.g., "db", "network", "parsing")
	Type     string             `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Severity ErrorInfo_Severity `protobuf:"varint,2,opt,name=severity,proto3,enum=consumer.ErrorInfo_Severity" json:"severity,omitempty"`
	// Error message
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Additional context
	Context       *_struct.Struct `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ErrorInfo) GetSeverity() ErrorInfo_Severity {
	if x != nil {
		return x.Severity
	}
	return ErrorInfo_UNKNOWN
}

func (x *ErrorInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorInfo) GetContext() *_struct.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

// Batch consume request for multiple messages
type BatchConsumeRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Messages []*DataMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	// Batch ID for correlation
	BatchId       string `protobuf:"bytes,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchConsumeRequest) Reset() {
	*x = BatchConsumeRequest{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchConsumeRequest) ProtoMessage() {}

func (x *BatchConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchConsumeRequest.ProtoReflect.Descriptor instead.
func (*BatchConsumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{4}
}

func (x *BatchConsumeRequest) GetMessages() []*DataMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *BatchConsumeRequest) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

// Batch consume response
type BatchConsumeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OverallSuccess bool                   `protobuf:"varint,1,opt,name=overall_success,json=overallSuccess,proto3" json:"overall_success,omitempty"`
	// Individual results for each message
	Results []*MessageResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	// Batch ID for correlation
	BatchId       string `protobuf:"bytes,3,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchConsumeResponse) Reset() {
	*x = BatchConsumeResponse{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchConsumeResponse) ProtoMessage() {}

func (x *BatchConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchConsumeResponse.ProtoReflect.Descriptor instead.
func (*BatchConsumeResponse) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{5}
}

func (x *BatchConsumeResponse) GetOverallSuccess() bool {
	if x != nil {
		return x.OverallSuccess
	}
	return false
}

func (x *BatchConsumeResponse) GetResults() []*MessageResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *BatchConsumeResponse) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

// Result for an individual message in a batch
type MessageResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorInfo     *ErrorInfo             `protobuf:"bytes,3,opt,name=error_info,json=errorInfo,proto3" json:"error_info,omitempty"`
	MessageIndex  int32                  `protobuf:"varint,4,opt,name=message_index,json=messageIndex,proto3" json:"message_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResult) Reset() {
	*x = MessageResult{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResult) ProtoMessage() {}

func (x *MessageResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResult.ProtoReflect.Descriptor instead.
func (*MessageResult) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{6}
}

func (x *MessageResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MessageResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *MessageResult) GetErrorInfo() *ErrorInfo {
	if x != nil {
		return x.ErrorInfo
	}
	return nil
}

func (x *MessageResult) GetMessageIndex() int32 {
	if x != nil {
		return x.MessageIndex
	}
	return 0
}

// Enhanced capabilities request
type CapabilitiesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional client information
	ClientInfo    map[string]string `protobuf:"bytes,1,rep,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{7}
}

func (x *CapabilitiesRequest) GetClientInfo() map[string]string {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

// Enhanced capabilities response
type CapabilitiesResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceName       string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceVersion    string                 `protobuf:"bytes,2,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"`
	SupportedFeatures []string               `protobuf:"bytes,3,rep,name=supported_features,json=supportedFeatures,proto3" json:"supported_features,omitempty"`
	// Rich capabilities information
	Capabilities *_struct.Struct `protobuf:"bytes,4,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Supported data formats
	SupportedFormats []string `protobuf:"bytes,5,rep,name=supported_formats,json=supportedFormats,proto3" json:"supported_formats,omitempty"`
	// Schema information provided by the consumer
	Schemas       []*SchemaInfo `protobuf:"bytes,6,rep,name=schemas,proto3" json:"schemas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{8}
}

func (x *CapabilitiesResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *CapabilitiesResponse) GetServiceVersion() string {
	if x != nil {
		return x.ServiceVersion
	}
	return ""
}

func (x *CapabilitiesResponse) GetSupportedFeatures() []string {
	if x != nil {
		return x.SupportedFeatures
	}
	return nil
}

func (x *CapabilitiesResponse) GetCapabilities() *_struct.Struct {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *CapabilitiesResponse) GetSupportedFormats() []string {
	if x != nil {
		return x.SupportedFormats
	}
	return nil
}

func (x *CapabilitiesResponse) GetSchemas() []*SchemaInfo {
	if x != nil {
		return x.Schemas
	}
	return nil
}

// Schema information
type SchemaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Definition    string                 `protobuf:"bytes,3,opt,name=definition,proto3" json:"definition,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"` // e.g., "sql", "json-schema", "avro"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaInfo) Reset() {
	*x = SchemaInfo{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaInfo) ProtoMessage() {}

func (x *SchemaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaInfo.ProtoReflect.Descriptor instead.
func (*SchemaInfo) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{9}
}

func (x *SchemaInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchemaInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SchemaInfo) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

func (x *SchemaInfo) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

// Enhanced configuration request
type ConfigureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Configuration as structured data
	Config         *_struct.Struct                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	ValidationMode ConfigureRequest_ValidationMode `protobuf:"varint,2,opt,name=validation_mode,json=validationMode,proto3,enum=consumer.ConfigureRequest_ValidationMode" json:"validation_mode,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{10}
}

func (x *ConfigureRequest) GetConfig() *_struct.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ConfigureRequest) GetValidationMode() ConfigureRequest_ValidationMode {
	if x != nil {
		return x.ValidationMode
	}
	return ConfigureRequest_VALIDATE_AND_APPLY
}

// Enhanced configuration response
type ConfigureResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Success      bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Validation issues
	ValidationIssues []*ValidationIssue `protobuf:"bytes,3,rep,name=validation_issues,json=validationIssues,proto3" json:"validation_issues,omitempty"`
	// Current configuration after changes
	CurrentConfig *_struct.Struct `protobuf:"bytes,4,opt,name=current_config,json=currentConfig,proto3" json:"current_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{11}
}

func (x *ConfigureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigureResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ConfigureResponse) GetValidationIssues() []*ValidationIssue {
	if x != nil {
		return x.ValidationIssues
	}
	return nil
}

func (x *ConfigureResponse) GetCurrentConfig() *_struct.Struct {
	if x != nil {
		return x.CurrentConfig
	}
	return nil
}

// Validation issue details
type ValidationIssue struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Severity      ValidationIssue_Severity `protobuf:"varint,1,opt,name=severity,proto3,enum=consumer.ValidationIssue_Severity" json:"severity,omitempty"`
	Field         string                   `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Message       string                   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationIssue) Reset() {
	*x = ValidationIssue{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationIssue) ProtoMessage() {}

func (x *ValidationIssue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationIssue.ProtoReflect.Descriptor instead.
func (*ValidationIssue) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{12}
}

func (x *ValidationIssue) GetSeverity() ValidationIssue_Severity {
	if x != nil {
		return x.Severity
	}
	return ValidationIssue_ERROR
}

func (x *ValidationIssue) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidationIssue) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Health check request
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detailed      bool                   `protobuf:"varint,1,opt,name=detailed,proto3" json:"detailed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{13}
}

func (x *HealthCheckRequest) GetDetailed() bool {
	if x != nil {
		return x.Detailed
	}
	return false
}

// Health check response
type HealthCheckResponse struct {
	state  protoimpl.MessageState            `protogen:"open.v1"`
	Status HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=consumer.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	// Detailed component health
	Components []*ComponentHealth `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"`
	// Service metrics
	Metrics       *_struct.Struct `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{14}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *HealthCheckResponse) GetComponents() []*ComponentHealth {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *HealthCheckResponse) GetMetrics() *_struct.Struct {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Component health information
type ComponentHealth struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	ComponentName string                            `protobuf:"bytes,1,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,2,opt,name=status,proto3,enum=consumer.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	Message       string                            `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentHealth) Reset() {
	*x = ComponentHealth{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentHealth) ProtoMessage() {}

func (x *ComponentHealth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentHealth.ProtoReflect.Descriptor instead.
func (*ComponentHealth) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{15}
}

func (x *ComponentHealth) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *ComponentHealth) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *ComponentHealth) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Advanced metrics request with filtering
type MetricsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional metric names to filter by
	MetricNames []string `protobuf:"bytes,1,rep,name=metric_names,json=metricNames,proto3" json:"metric_names,omitempty"`
	// Include detailed metrics breakdown
	Detailed      bool `protobuf:"varint,2,opt,name=detailed,proto3" json:"detailed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{16}
}

func (x *MetricsRequest) GetMetricNames() []string {
	if x != nil {
		return x.MetricNames
	}
	return nil
}

func (x *MetricsRequest) GetDetailed() bool {
	if x != nil {
		return x.Detailed
	}
	return false
}

// Enhanced metrics response
type MetricsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metrics as structured data
	Metrics *_struct.Struct `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	// Last updated timestamp
	UpdatedAt     *timestamp.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{17}
}

func (x *MetricsResponse) GetMetrics() *_struct.Struct {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *MetricsResponse) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Lifecycle control request
type LifecycleRequest struct {
	state     protoimpl.MessageState     `protogen:"open.v1"`
	Operation LifecycleRequest_Operation `protobuf:"varint,1,opt,name=operation,proto3,enum=consumer.LifecycleRequest_Operation" json:"operation,omitempty"`
	// Operation parameters
	Parameters    *_struct.Struct `protobuf:"bytes,2,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LifecycleRequest) Reset() {
	*x = LifecycleRequest{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifecycleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleRequest) ProtoMessage() {}

func (x *LifecycleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleRequest.ProtoReflect.Descriptor instead.
func (*LifecycleRequest) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{18}
}

func (x *LifecycleRequest) GetOperation() LifecycleRequest_Operation {
	if x != nil {
		return x.Operation
	}
	return LifecycleRequest_INITIALIZE
}

func (x *LifecycleRequest) GetParameters() *_struct.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// Lifecycle control response
type LifecycleResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Current status after operation
	Status        string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LifecycleResponse) Reset() {
	*x = LifecycleResponse{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifecycleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleResponse) ProtoMessage() {}

func (x *LifecycleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleResponse.ProtoReflect.Descriptor instead.
func (*LifecycleResponse) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{19}
}

func (x *LifecycleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LifecycleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LifecycleResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_consumer_consumer_proto protoreflect.FileDescriptor

const file_proto_consumer_consumer_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/consumer/consumer.proto\x12\bconsumer\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xd8\x01\n" +
	"\vDataMessage\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x123\n" +
	"\bmetadata\x18\x02 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"message_id\x18\x05 \x01(\tR\tmessageId\"`\n" +
	"\x0eConsumeRequest\x12/\n" +
	"\amessage\x18\x01 \x01(\v2\x15.consumer.DataMessageR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"\xa3\x01\n" +
	"\x0fConsumeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x122\n" +
	"\n" +
	"error_info\x18\x03 \x01(\v2\x13.consumer.ErrorInfoR\terrorInfo\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"\xec\x01\n" +
	"\tErrorInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x128\n" +
	"\bseverity\x18\x02 \x01(\x0e2\x1c.consumer.ErrorInfo.SeverityR\bseverity\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x121\n" +
	"\acontext\x18\x04 \x01(\v2\x17.google.protobuf.StructR\acontext\"D\n" +
	"\bSeverity\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05FATAL\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02\x12\v\n" +
	"\aWARNING\x10\x03\x12\b\n" +
	"\x04INFO\x10\x04\"c\n" +
	"\x13BatchConsumeRequest\x121\n" +
	"\bmessages\x18\x01 \x03(\v2\x15.consumer.DataMessageR\bmessages\x12\x19\n" +
	"\bbatch_id\x18\x02 \x01(\tR\abatchId\"\x8d\x01\n" +
	"\x14BatchConsumeResponse\x12'\n" +
	"\x0foverall_success\x18\x01 \x01(\bR\x0eoverallSuccess\x121\n" +
	"\aresults\x18\x02 \x03(\v2\x17.consumer.MessageResultR\aresults\x12\x19\n" +
	"\bbatch_id\x18\x03 \x01(\tR\abatchId\"\xa7\x01\n" +
	"\rMessageResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x122\n" +
	"\n" +
	"error_info\x18\x03 \x01(\v2\x13.consumer.ErrorInfoR\terrorInfo\x12#\n" +
	"\rmessage_index\x18\x04 \x01(\x05R\fmessageIndex\"\xa4\x01\n" +
	"\x13CapabilitiesRequest\x12N\n" +
	"\vclient_info\x18\x01 \x03(\v2-.consumer.CapabilitiesRequest.ClientInfoEntryR\n" +
	"clientInfo\x1a=\n" +
	"\x0fClientInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xab\x02\n" +
	"\x14CapabilitiesResponse\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12'\n" +
	"\x0fservice_version\x18\x02 \x01(\tR\x0eserviceVersion\x12-\n" +
	"\x12supported_features\x18\x03 \x03(\tR\x11supportedFeatures\x12;\n" +
	"\fcapabilities\x18\x04 \x01(\v2\x17.google.protobuf.StructR\fcapabilities\x12+\n" +
	"\x11supported_formats\x18\x05 \x03(\tR\x10supportedFormats\x12.\n" +
	"\aschemas\x18\x06 \x03(\v2\x14.consumer.SchemaInfoR\aschemas\"z\n" +
	"\n" +
	"SchemaInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"definition\x18\x03 \x01(\tR\n" +
	"definition\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\"\xd4\x01\n" +
	"\x10ConfigureRequest\x12/\n" +
	"\x06config\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06config\x12R\n" +
	"\x0fvalidation_mode\x18\x02 \x01(\x0e2).consumer.ConfigureRequest.ValidationModeR\x0evalidationMode\";\n" +
	"\x0eValidationMode\x12\x16\n" +
	"\x12VALIDATE_AND_APPLY\x10\x00\x12\x11\n" +
	"\rVALIDATE_ONLY\x10\x01\"\xda\x01\n" +
	"\x11ConfigureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12F\n" +
	"\x11validation_issues\x18\x03 \x03(\v2\x19.consumer.ValidationIssueR\x10validationIssues\x12>\n" +
	"\x0ecurrent_config\x18\x04 \x01(\v2\x17.google.protobuf.StructR\rcurrentConfig\"\xaf\x01\n" +
	"\x0fValidationIssue\x12>\n" +
	"\bseverity\x18\x01 \x01(\x0e2\".consumer.ValidationIssue.SeverityR\bseverity\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\",\n" +
	"\bSeverity\x12\t\n" +
	"\x05ERROR\x10\x00\x12\v\n" +
	"\aWARNING\x10\x01\x12\b\n" +
	"\x04INFO\x10\x02\"0\n" +
	"\x12HealthCheckRequest\x12\x1a\n" +
	"\bdetailed\x18\x01 \x01(\bR\bdetailed\"\xb5\x02\n" +
	"\x13HealthCheckResponse\x12C\n" +
	"\x06status\x18\x01 \x01(\x0e2+.consumer.HealthCheckResponse.ServingStatusR\x06status\x129\n" +
	"\n" +
	"components\x18\x02 \x03(\v2\x19.consumer.ComponentHealthR\n" +
	"components\x121\n" +
	"\ametrics\x18\x03 \x01(\v2\x17.google.protobuf.StructR\ametrics\"k\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\x12\x13\n" +
	"\x0fSERVICE_UNKNOWN\x10\x03\x12\f\n" +
	"\bSTARTING\x10\x04\x12\f\n" +
	"\bSTOPPING\x10\x05\"\x97\x01\n" +
	"\x0fComponentHealth\x12%\n" +
	"\x0ecomponent_name\x18\x01 \x01(\tR\rcomponentName\x12C\n" +
	"\x06status\x18\x02 \x01(\x0e2+.consumer.HealthCheckResponse.ServingStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"O\n" +
	"\x0eMetricsRequest\x12!\n" +
	"\fmetric_names\x18\x01 \x03(\tR\vmetricNames\x12\x1a\n" +
	"\bdetailed\x18\x02 \x01(\bR\bdetailed\"\x7f\n" +
	"\x0fMetricsResponse\x121\n" +
	"\ametrics\x18\x01 \x01(\v2\x17.google.protobuf.StructR\ametrics\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xdc\x01\n" +
	"\x10LifecycleRequest\x12B\n" +
	"\toperation\x18\x01 \x01(\x0e2$.consumer.LifecycleRequest.OperationR\toperation\x127\n" +
	"\n" +
	"parameters\x18\x02 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\"K\n" +
	"\tOperation\x12\x0e\n" +
	"\n" +
	"INITIALIZE\x10\x00\x12\f\n" +
	"\bSHUTDOWN\x10\x01\x12\t\n" +
	"\x05PAUSE\x10\x02\x12\n" +
	"\n" +
	"\x06RESUME\x10\x03\x12\t\n" +
	"\x05RESET\x10\x04\"_\n" +
	"\x11LifecycleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status2\xd5\x04\n" +
	"\x0fConsumerService\x12P\n" +
	"\x0fGetCapabilities\x12\x1d.consumer.CapabilitiesRequest\x1a\x1e.consumer.CapabilitiesResponse\x12D\n" +
	"\tConfigure\x12\x1a.consumer.ConfigureRequest\x1a\x1b.consumer.ConfigureResponse\x12>\n" +
	"\aConsume\x12\x18.consumer.ConsumeRequest\x1a\x19.consumer.ConsumeResponse\x12M\n" +
	"\fBatchConsume\x12\x1d.consumer.BatchConsumeRequest\x1a\x1e.consumer.BatchConsumeResponse\x12H\n" +
	"\rStreamConsume\x12\x18.consumer.ConsumeRequest\x1a\x19.consumer.ConsumeResponse(\x010\x01\x12J\n" +
	"\vCheckHealth\x12\x1c.consumer.HealthCheckRequest\x1a\x1d.consumer.HealthCheckResponse\x12A\n" +
	"\n" +
	"GetMetrics\x12\x18.consumer.MetricsRequest\x1a\x19.consumer.MetricsResponse\x12B\n" +
	"\aControl\x12\x1a.consumer.LifecycleRequest\x1a\x1b.consumer.LifecycleResponseB1Z/github.com/withObsrvr/flow-proto/proto/consumerb\x06proto3"

var (
	file_proto_consumer_consumer_proto_rawDescOnce sync.Once
	file_proto_consumer_consumer_proto_rawDescData []byte
)

func file_proto_consumer_consumer_proto_rawDescGZIP() []byte {
	file_proto_consumer_consumer_proto_rawDescOnce.Do(func() {
		file_proto_consumer_consumer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_consumer_consumer_proto_rawDesc), len(file_proto_consumer_consumer_proto_rawDesc)))
	})
	return file_proto_consumer_consumer_proto_rawDescData
}

var file_proto_consumer_consumer_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_consumer_consumer_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_consumer_consumer_proto_goTypes = []any{
	(ErrorInfo_Severity)(0),                // 0: consumer.ErrorInfo.Severity
	(ConfigureRequest_ValidationMode)(0),   // 1: consumer.ConfigureRequest.ValidationMode
	(ValidationIssue_Severity)(0),          // 2: consumer.ValidationIssue.Severity
	(HealthCheckResponse_ServingStatus)(0), // 3: consumer.HealthCheckResponse.ServingStatus
	(LifecycleRequest_Operation)(0),        // 4: consumer.LifecycleRequest.Operation
	(*DataMessage)(nil),                    // 5: consumer.DataMessage
	(*ConsumeRequest)(nil),                 // 6: consumer.ConsumeRequest
	(*ConsumeResponse)(nil),                // 7: consumer.ConsumeResponse
	(*ErrorInfo)(nil),                      // 8: consumer.ErrorInfo
	(*BatchConsumeRequest)(nil),            // 9: consumer.BatchConsumeRequest
	(*BatchConsumeResponse)(nil),           // 10: consumer.BatchConsumeResponse
	(*MessageResult)(nil),                  // 11: consumer.MessageResult
	(*CapabilitiesRequest)(nil),            // 12: consumer.CapabilitiesRequest
	(*CapabilitiesResponse)(nil),           // 13: consumer.CapabilitiesResponse
	(*SchemaInfo)(nil),                     // 14: consumer.SchemaInfo
	(*ConfigureRequest)(nil),               // 15: consumer.ConfigureRequest
	(*ConfigureResponse)(nil),              // 16: consumer.ConfigureResponse
	(*ValidationIssue)(nil),                // 17: consumer.ValidationIssue
	(*HealthCheckRequest)(nil),             // 18: consumer.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 19: consumer.HealthCheckResponse
	(*ComponentHealth)(nil),                // 20: consumer.ComponentHealth
	(*MetricsRequest)(nil),                 // 21: consumer.MetricsRequest
	(*MetricsResponse)(nil),                // 22: consumer.MetricsResponse
	(*LifecycleRequest)(nil),               // 23: consumer.LifecycleRequest
	(*LifecycleResponse)(nil),              // 24: consumer.LifecycleResponse
	nil,                                    // 25: consumer.CapabilitiesRequest.ClientInfoEntry
	(*_struct.Struct)(nil),                 // 26: google.protobuf.Struct
	(*timestamp.Timestamp)(nil),            // 27: google.protobuf.Timestamp
}
var file_proto_consumer_consumer_proto_depIdxs = []int32{
	26, // 0: consumer.DataMessage.metadata:type_name -> google.protobuf.Struct
	27, // 1: consumer.DataMessage.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 2: consumer.ConsumeRequest.message:type_name -> consumer.DataMessage
	8,  // 3: consumer.ConsumeResponse.error_info:type_name -> consumer.ErrorInfo
	0,  // 4: consumer.ErrorInfo.severity:type_name -> consumer.ErrorInfo.Severity
	26, // 5: consumer.ErrorInfo.context:type_name -> google.protobuf.Struct
	5,  // 6: consumer.BatchConsumeRequest.messages:type_name -> consumer.DataMessage
	11, // 7: consumer.BatchConsumeResponse.results:type_name -> consumer.MessageResult
	8,  // 8: consumer.MessageResult.error_info:type_name -> consumer.ErrorInfo
	25, // 9: consumer.CapabilitiesRequest.client_info:type_name -> consumer.CapabilitiesRequest.ClientInfoEntry
	26, // 10: consumer.CapabilitiesResponse.capabilities:type_name -> google.protobuf.Struct
	14, // 11: consumer.CapabilitiesResponse.schemas:type_name -> consumer.SchemaInfo
	26, // 12: consumer.ConfigureRequest.config:type_name -> google.protobuf.Struct
	1,  // 13: consumer.ConfigureRequest.validation_mode:type_name -> consumer.ConfigureRequest.ValidationMode
	17, // 14: consumer.ConfigureResponse.validation_issues:type_name -> consumer.ValidationIssue
	26, // 15: consumer.ConfigureResponse.current_config:type_name -> google.protobuf.Struct
	2,  // 16: consumer.ValidationIssue.severity:type_name -> consumer.ValidationIssue.Severity
	3,  // 17: consumer.HealthCheckResponse.status:type_name -> consumer.HealthCheckResponse.ServingStatus
	20, // 18: consumer.HealthCheckResponse.components:type_name -> consumer.ComponentHealth
	26, // 19: consumer.HealthCheckResponse.metrics:type_name -> google.protobuf.Struct
	3,  // 20: consumer.ComponentHealth.status:type_name -> consumer.HealthCheckResponse.ServingStatus
	26, // 21: consumer.MetricsResponse.metrics:type_name -> google.protobuf.Struct
	27, // 22: consumer.MetricsResponse.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 23: consumer.LifecycleRequest.operation:type_name -> consumer.LifecycleRequest.Operation
	26, // 24: consumer.LifecycleRequest.parameters:type_name -> google.protobuf.Struct
	12, // 25: consumer.ConsumerService.GetCapabilities:input_type -> consumer.CapabilitiesRequest
	15, // 26: consumer.ConsumerService.Configure:input_type -> consumer.ConfigureRequest
	6,  // 27: consumer.ConsumerService.Consume:input_type -> consumer.ConsumeRequest
	9,  // 28: consumer.ConsumerService.BatchConsume:input_type -> consumer.BatchConsumeRequest
	6,  // 29: consumer.ConsumerService.StreamConsume:input_type -> consumer.ConsumeRequest
	18, // 30: consumer.ConsumerService.CheckHealth:input_type -> consumer.HealthCheckRequest
	21, // 31: consumer.ConsumerService.GetMetrics:input_type -> consumer.MetricsRequest
	23, // 32: consumer.ConsumerService.Control:input_type -> consumer.LifecycleRequest
	13, // 33: consumer.ConsumerService.GetCapabilities:output_type -> consumer.CapabilitiesResponse
	16, // 34: consumer.ConsumerService.Configure:output_type -> consumer.ConfigureResponse
	7,  // 35: consumer.ConsumerService.Consume:output_type -> consumer.ConsumeResponse
	10, // 36: consumer.ConsumerService.BatchConsume:output_type -> consumer.BatchConsumeResponse
	7,  // 37: consumer.ConsumerService.StreamConsume:output_type -> consumer.ConsumeResponse
	19, // 38: consumer.ConsumerService.CheckHealth:output_type -> consumer.HealthCheckResponse
	22, // 39: consumer.ConsumerService.GetMetrics:output_type -> consumer.MetricsResponse
	24, // 40: consumer.ConsumerService.Control:output_type -> consumer.LifecycleResponse
	33, // [33:41] is the sub-list for method output_type
	25, // [25:33] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_proto_consumer_consumer_proto_init() }
func file_proto_consumer_consumer_proto_init() {
	if File_proto_consumer_consumer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_consumer_consumer_proto_rawDesc), len(file_proto_consumer_consumer_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_consumer_consumer_proto_goTypes,
		DependencyIndexes: file_proto_consumer_consumer_proto_depIdxs,
		EnumInfos:         file_proto_consumer_consumer_proto_enumTypes,
		MessageInfos:      file_proto_consumer_consumer_proto_msgTypes,
	}.Build()
	File_proto_consumer_consumer_proto = out.File
	file_proto_consumer_consumer_proto_goTypes = nil
	file_proto_consumer_consumer_proto_depIdxs = nil
}
