// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/consumer/consumer.proto

package consumer

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DataMessage represents the basic message that the consumer will receive.
type DataMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The raw data payload.
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// Additional metadata as key-value pairs.
	Metadata map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Timestamp when the message was created.
	Timestamp     *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataMessage) Reset() {
	*x = DataMessage{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataMessage) ProtoMessage() {}

func (x *DataMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataMessage.ProtoReflect.Descriptor instead.
func (*DataMessage) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{0}
}

func (x *DataMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DataMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DataMessage) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// ConsumeRequest wraps a DataMessage to be consumed.
type ConsumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *DataMessage           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{1}
}

func (x *ConsumeRequest) GetMessage() *DataMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

// ConsumeResponse acknowledges the consumption of a message.
type ConsumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeResponse) Reset() {
	*x = ConsumeResponse{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeResponse) ProtoMessage() {}

func (x *ConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeResponse.ProtoReflect.Descriptor instead.
func (*ConsumeResponse) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{2}
}

func (x *ConsumeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConsumeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Requests and responses for capabilities.
type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{3}
}

type CapabilitiesResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceName       string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceVersion    string                 `protobuf:"bytes,2,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"`
	SupportedFeatures []string               `protobuf:"bytes,3,rep,name=supported_features,json=supportedFeatures,proto3" json:"supported_features,omitempty"`
	// Additional capabilities can be included as key-value pairs.
	Capabilities  map[string]string `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{4}
}

func (x *CapabilitiesResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *CapabilitiesResponse) GetServiceVersion() string {
	if x != nil {
		return x.ServiceVersion
	}
	return ""
}

func (x *CapabilitiesResponse) GetSupportedFeatures() []string {
	if x != nil {
		return x.SupportedFeatures
	}
	return nil
}

func (x *CapabilitiesResponse) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// Requests and responses for configuration.
type ConfigureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Configuration settings as key-value pairs.
	Config        map[string]string `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigureRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigureResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Request and response for retrieving consumer metrics.
type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{7}
}

type MetricsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metrics reported as key-value pairs.
	Metrics       map[string]string `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{8}
}

func (x *MetricsResponse) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_proto_consumer_consumer_proto protoreflect.FileDescriptor

const file_proto_consumer_consumer_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/consumer/consumer.proto\x12\bconsumer\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdf\x01\n" +
	"\vDataMessage\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12?\n" +
	"\bmetadata\x18\x02 \x03(\v2#.consumer.DataMessage.MetadataEntryR\bmetadata\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\x0eConsumeRequest\x12/\n" +
	"\amessage\x18\x01 \x01(\v2\x15.consumer.DataMessageR\amessage\"P\n" +
	"\x0fConsumeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x15\n" +
	"\x13CapabilitiesRequest\"\xa8\x02\n" +
	"\x14CapabilitiesResponse\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12'\n" +
	"\x0fservice_version\x18\x02 \x01(\tR\x0eserviceVersion\x12-\n" +
	"\x12supported_features\x18\x03 \x03(\tR\x11supportedFeatures\x12T\n" +
	"\fcapabilities\x18\x04 \x03(\v20.consumer.CapabilitiesResponse.CapabilitiesEntryR\fcapabilities\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x01\n" +
	"\x10ConfigureRequest\x12>\n" +
	"\x06config\x18\x01 \x03(\v2&.consumer.ConfigureRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x11ConfigureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x10\n" +
	"\x0eMetricsRequest\"\x8f\x01\n" +
	"\x0fMetricsResponse\x12@\n" +
	"\ametrics\x18\x01 \x03(\v2&.consumer.MetricsResponse.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xac\x02\n" +
	"\x0fConsumerService\x12P\n" +
	"\x0fGetCapabilities\x12\x1d.consumer.CapabilitiesRequest\x1a\x1e.consumer.CapabilitiesResponse\x12D\n" +
	"\tConfigure\x12\x1a.consumer.ConfigureRequest\x1a\x1b.consumer.ConfigureResponse\x12>\n" +
	"\aConsume\x12\x18.consumer.ConsumeRequest\x1a\x19.consumer.ConsumeResponse\x12A\n" +
	"\n" +
	"GetMetrics\x12\x18.consumer.MetricsRequest\x1a\x19.consumer.MetricsResponseB1Z/github.com/withObsrvr/flow-proto/proto/consumerb\x06proto3"

var (
	file_proto_consumer_consumer_proto_rawDescOnce sync.Once
	file_proto_consumer_consumer_proto_rawDescData []byte
)

func file_proto_consumer_consumer_proto_rawDescGZIP() []byte {
	file_proto_consumer_consumer_proto_rawDescOnce.Do(func() {
		file_proto_consumer_consumer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_consumer_consumer_proto_rawDesc), len(file_proto_consumer_consumer_proto_rawDesc)))
	})
	return file_proto_consumer_consumer_proto_rawDescData
}

var file_proto_consumer_consumer_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_consumer_consumer_proto_goTypes = []any{
	(*DataMessage)(nil),          // 0: consumer.DataMessage
	(*ConsumeRequest)(nil),       // 1: consumer.ConsumeRequest
	(*ConsumeResponse)(nil),      // 2: consumer.ConsumeResponse
	(*CapabilitiesRequest)(nil),  // 3: consumer.CapabilitiesRequest
	(*CapabilitiesResponse)(nil), // 4: consumer.CapabilitiesResponse
	(*ConfigureRequest)(nil),     // 5: consumer.ConfigureRequest
	(*ConfigureResponse)(nil),    // 6: consumer.ConfigureResponse
	(*MetricsRequest)(nil),       // 7: consumer.MetricsRequest
	(*MetricsResponse)(nil),      // 8: consumer.MetricsResponse
	nil,                          // 9: consumer.DataMessage.MetadataEntry
	nil,                          // 10: consumer.CapabilitiesResponse.CapabilitiesEntry
	nil,                          // 11: consumer.ConfigureRequest.ConfigEntry
	nil,                          // 12: consumer.MetricsResponse.MetricsEntry
	(*timestamp.Timestamp)(nil),  // 13: google.protobuf.Timestamp
}
var file_proto_consumer_consumer_proto_depIdxs = []int32{
	9,  // 0: consumer.DataMessage.metadata:type_name -> consumer.DataMessage.MetadataEntry
	13, // 1: consumer.DataMessage.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 2: consumer.ConsumeRequest.message:type_name -> consumer.DataMessage
	10, // 3: consumer.CapabilitiesResponse.capabilities:type_name -> consumer.CapabilitiesResponse.CapabilitiesEntry
	11, // 4: consumer.ConfigureRequest.config:type_name -> consumer.ConfigureRequest.ConfigEntry
	12, // 5: consumer.MetricsResponse.metrics:type_name -> consumer.MetricsResponse.MetricsEntry
	3,  // 6: consumer.ConsumerService.GetCapabilities:input_type -> consumer.CapabilitiesRequest
	5,  // 7: consumer.ConsumerService.Configure:input_type -> consumer.ConfigureRequest
	1,  // 8: consumer.ConsumerService.Consume:input_type -> consumer.ConsumeRequest
	7,  // 9: consumer.ConsumerService.GetMetrics:input_type -> consumer.MetricsRequest
	4,  // 10: consumer.ConsumerService.GetCapabilities:output_type -> consumer.CapabilitiesResponse
	6,  // 11: consumer.ConsumerService.Configure:output_type -> consumer.ConfigureResponse
	2,  // 12: consumer.ConsumerService.Consume:output_type -> consumer.ConsumeResponse
	8,  // 13: consumer.ConsumerService.GetMetrics:output_type -> consumer.MetricsResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_consumer_consumer_proto_init() }
func file_proto_consumer_consumer_proto_init() {
	if File_proto_consumer_consumer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_consumer_consumer_proto_rawDesc), len(file_proto_consumer_consumer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_consumer_consumer_proto_goTypes,
		DependencyIndexes: file_proto_consumer_consumer_proto_depIdxs,
		MessageInfos:      file_proto_consumer_consumer_proto_msgTypes,
	}.Build()
	File_proto_consumer_consumer_proto = out.File
	file_proto_consumer_consumer_proto_goTypes = nil
	file_proto_consumer_consumer_proto_depIdxs = nil
}
