// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/processor/processor.proto

package processor

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DataMessage represents the basic message exchanged with the processor.
type DataMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The raw data payload.
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// Key-value metadata associated with the message.
	Metadata map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The time at which the message was created.
	Timestamp     *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataMessage) Reset() {
	*x = DataMessage{}
	mi := &file_proto_processor_processor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataMessage) ProtoMessage() {}

func (x *DataMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_processor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataMessage.ProtoReflect.Descriptor instead.
func (*DataMessage) Descriptor() ([]byte, []int) {
	return file_proto_processor_processor_proto_rawDescGZIP(), []int{0}
}

func (x *DataMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DataMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DataMessage) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// CapabilitiesRequest is empty since no parameters are needed.
type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_proto_processor_processor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_processor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_processor_processor_proto_rawDescGZIP(), []int{1}
}

// CapabilitiesResponse reports the processor's capabilities.
type CapabilitiesResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceName       string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceVersion    string                 `protobuf:"bytes,2,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"`
	SupportedFeatures []string               `protobuf:"bytes,3,rep,name=supported_features,json=supportedFeatures,proto3" json:"supported_features,omitempty"`
	// Additional capabilities can be provided as key-value pairs.
	Capabilities  map[string]string `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_proto_processor_processor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_processor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_processor_processor_proto_rawDescGZIP(), []int{2}
}

func (x *CapabilitiesResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *CapabilitiesResponse) GetServiceVersion() string {
	if x != nil {
		return x.ServiceVersion
	}
	return ""
}

func (x *CapabilitiesResponse) GetSupportedFeatures() []string {
	if x != nil {
		return x.SupportedFeatures
	}
	return nil
}

func (x *CapabilitiesResponse) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// ConfigureRequest carries configuration settings as key-value pairs.
type ConfigureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_proto_processor_processor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_processor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_proto_processor_processor_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigureRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

// ConfigureResponse returns success status and an optional error message.
type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_proto_processor_processor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_processor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_proto_processor_processor_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigureResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_processor_processor_proto protoreflect.FileDescriptor

const file_proto_processor_processor_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/processor/processor.proto\x12\tprocessor\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe0\x01\n" +
	"\vDataMessage\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12@\n" +
	"\bmetadata\x18\x02 \x03(\v2$.processor.DataMessage.MetadataEntryR\bmetadata\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x15\n" +
	"\x13CapabilitiesRequest\"\xa9\x02\n" +
	"\x14CapabilitiesResponse\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12'\n" +
	"\x0fservice_version\x18\x02 \x01(\tR\x0eserviceVersion\x12-\n" +
	"\x12supported_features\x18\x03 \x03(\tR\x11supportedFeatures\x12U\n" +
	"\fcapabilities\x18\x04 \x03(\v21.processor.CapabilitiesResponse.CapabilitiesEntryR\fcapabilities\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x01\n" +
	"\x10ConfigureRequest\x12?\n" +
	"\x06config\x18\x01 \x03(\v2'.processor.ConfigureRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x11ConfigureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2\xed\x01\n" +
	"\x10ProcessorService\x12R\n" +
	"\x0fGetCapabilities\x12\x1e.processor.CapabilitiesRequest\x1a\x1f.processor.CapabilitiesResponse\x12F\n" +
	"\tConfigure\x12\x1b.processor.ConfigureRequest\x1a\x1c.processor.ConfigureResponse\x12=\n" +
	"\aProcess\x12\x16.processor.DataMessage\x1a\x16.processor.DataMessage(\x010\x01B2Z0github.com/withObsrvr/flow-proto/proto/processorb\x06proto3"

var (
	file_proto_processor_processor_proto_rawDescOnce sync.Once
	file_proto_processor_processor_proto_rawDescData []byte
)

func file_proto_processor_processor_proto_rawDescGZIP() []byte {
	file_proto_processor_processor_proto_rawDescOnce.Do(func() {
		file_proto_processor_processor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_processor_processor_proto_rawDesc), len(file_proto_processor_processor_proto_rawDesc)))
	})
	return file_proto_processor_processor_proto_rawDescData
}

var file_proto_processor_processor_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_processor_processor_proto_goTypes = []any{
	(*DataMessage)(nil),          // 0: processor.DataMessage
	(*CapabilitiesRequest)(nil),  // 1: processor.CapabilitiesRequest
	(*CapabilitiesResponse)(nil), // 2: processor.CapabilitiesResponse
	(*ConfigureRequest)(nil),     // 3: processor.ConfigureRequest
	(*ConfigureResponse)(nil),    // 4: processor.ConfigureResponse
	nil,                          // 5: processor.DataMessage.MetadataEntry
	nil,                          // 6: processor.CapabilitiesResponse.CapabilitiesEntry
	nil,                          // 7: processor.ConfigureRequest.ConfigEntry
	(*timestamp.Timestamp)(nil),  // 8: google.protobuf.Timestamp
}
var file_proto_processor_processor_proto_depIdxs = []int32{
	5, // 0: processor.DataMessage.metadata:type_name -> processor.DataMessage.MetadataEntry
	8, // 1: processor.DataMessage.timestamp:type_name -> google.protobuf.Timestamp
	6, // 2: processor.CapabilitiesResponse.capabilities:type_name -> processor.CapabilitiesResponse.CapabilitiesEntry
	7, // 3: processor.ConfigureRequest.config:type_name -> processor.ConfigureRequest.ConfigEntry
	1, // 4: processor.ProcessorService.GetCapabilities:input_type -> processor.CapabilitiesRequest
	3, // 5: processor.ProcessorService.Configure:input_type -> processor.ConfigureRequest
	0, // 6: processor.ProcessorService.Process:input_type -> processor.DataMessage
	2, // 7: processor.ProcessorService.GetCapabilities:output_type -> processor.CapabilitiesResponse
	4, // 8: processor.ProcessorService.Configure:output_type -> processor.ConfigureResponse
	0, // 9: processor.ProcessorService.Process:output_type -> processor.DataMessage
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_processor_processor_proto_init() }
func file_proto_processor_processor_proto_init() {
	if File_proto_processor_processor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_processor_processor_proto_rawDesc), len(file_proto_processor_processor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_processor_processor_proto_goTypes,
		DependencyIndexes: file_proto_processor_processor_proto_depIdxs,
		MessageInfos:      file_proto_processor_processor_proto_msgTypes,
	}.Build()
	File_proto_processor_processor_proto = out.File
	file_proto_processor_processor_proto_goTypes = nil
	file_proto_processor_processor_proto_depIdxs = nil
}
