name: proto-check

on:
  push:
    paths: [ 'proto/**.proto', 'Makefile', 'flake.nix', 'go.mod' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - run: nix develop --command make proto
      - run: git diff --exit-code   # fails if generated code not up to date
