// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/source/source.proto

package source

import (
	_struct "github.com/golang/protobuf/ptypes/struct"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Optional configuration validation mode
type ConfigureRequest_ValidationMode int32

const (
	ConfigureRequest_VALIDATE_AND_APPLY ConfigureRequest_ValidationMode = 0 // Validate and apply if valid
	ConfigureRequest_VALIDATE_ONLY      ConfigureRequest_ValidationMode = 1 // Only validate, don't apply
)

// Enum value maps for ConfigureRequest_ValidationMode.
var (
	ConfigureRequest_ValidationMode_name = map[int32]string{
		0: "VALIDATE_AND_APPLY",
		1: "VALIDATE_ONLY",
	}
	ConfigureRequest_ValidationMode_value = map[string]int32{
		"VALIDATE_AND_APPLY": 0,
		"VALIDATE_ONLY":      1,
	}
)

func (x ConfigureRequest_ValidationMode) Enum() *ConfigureRequest_ValidationMode {
	p := new(ConfigureRequest_ValidationMode)
	*p = x
	return p
}

func (x ConfigureRequest_ValidationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigureRequest_ValidationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_source_source_proto_enumTypes[0].Descriptor()
}

func (ConfigureRequest_ValidationMode) Type() protoreflect.EnumType {
	return &file_proto_source_source_proto_enumTypes[0]
}

func (x ConfigureRequest_ValidationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigureRequest_ValidationMode.Descriptor instead.
func (ConfigureRequest_ValidationMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_source_source_proto_rawDescGZIP(), []int{3, 0}
}

type ValidationIssue_Severity int32

const (
	ValidationIssue_ERROR   ValidationIssue_Severity = 0
	ValidationIssue_WARNING ValidationIssue_Severity = 1
	ValidationIssue_INFO    ValidationIssue_Severity = 2
)

// Enum value maps for ValidationIssue_Severity.
var (
	ValidationIssue_Severity_name = map[int32]string{
		0: "ERROR",
		1: "WARNING",
		2: "INFO",
	}
	ValidationIssue_Severity_value = map[string]int32{
		"ERROR":   0,
		"WARNING": 1,
		"INFO":    2,
	}
)

func (x ValidationIssue_Severity) Enum() *ValidationIssue_Severity {
	p := new(ValidationIssue_Severity)
	*p = x
	return p
}

func (x ValidationIssue_Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidationIssue_Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_source_source_proto_enumTypes[1].Descriptor()
}

func (ValidationIssue_Severity) Type() protoreflect.EnumType {
	return &file_proto_source_source_proto_enumTypes[1]
}

func (x ValidationIssue_Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidationIssue_Severity.Descriptor instead.
func (ValidationIssue_Severity) EnumDescriptor() ([]byte, []int) {
	return file_proto_source_source_proto_rawDescGZIP(), []int{5, 0}
}

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN         HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING         HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING     HealthCheckResponse_ServingStatus = 2
	HealthCheckResponse_SERVICE_UNKNOWN HealthCheckResponse_ServingStatus = 3
	HealthCheckResponse_STARTING        HealthCheckResponse_ServingStatus = 4
	HealthCheckResponse_STOPPING        HealthCheckResponse_ServingStatus = 5
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
		3: "SERVICE_UNKNOWN",
		4: "STARTING",
		5: "STOPPING",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":         0,
		"SERVING":         1,
		"NOT_SERVING":     2,
		"SERVICE_UNKNOWN": 3,
		"STARTING":        4,
		"STOPPING":        5,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_source_source_proto_enumTypes[2].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_proto_source_source_proto_enumTypes[2]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_source_source_proto_rawDescGZIP(), []int{16, 0}
}

type StreamCommand_CommandType int32

const (
	StreamCommand_PAUSE       StreamCommand_CommandType = 0
	StreamCommand_RESUME      StreamCommand_CommandType = 1
	StreamCommand_FILTER      StreamCommand_CommandType = 2
	StreamCommand_SEEK        StreamCommand_CommandType = 3
	StreamCommand_ACKNOWLEDGE StreamCommand_CommandType = 4
)

// Enum value maps for StreamCommand_CommandType.
var (
	StreamCommand_CommandType_name = map[int32]string{
		0: "PAUSE",
		1: "RESUME",
		2: "FILTER",
		3: "SEEK",
		4: "ACKNOWLEDGE",
	}
	StreamCommand_CommandType_value = map[string]int32{
		"PAUSE":       0,
		"RESUME":      1,
		"FILTER":      2,
		"SEEK":        3,
		"ACKNOWLEDGE": 4,
	}
)

func (x StreamCommand_CommandType) Enum() *StreamCommand_CommandType {
	p := new(StreamCommand_CommandType)
	*p = x
	return p
}

func (x StreamCommand_CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamCommand_CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_source_source_proto_enumTypes[3].Descriptor()
}

func (StreamCommand_CommandType) Type() protoreflect.EnumType {
	return &file_proto_source_source_proto_enumTypes[3]
}

func (x StreamCommand_CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamCommand_CommandType.Descriptor instead.
func (StreamCommand_CommandType) EnumDescriptor() ([]byte, []int) {
	return file_proto_source_source_proto_rawDescGZIP(), []int{20, 0}
}

// DataMessage is the basic message exchanged from a Source.
// Enhanced to support multiple payload types and richer metadata.
type DataMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The raw data payload.
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// Metadata about the message, now supporting complex values.
	// Values can be strings, numbers, booleans, or nested objects.
	Metadata *_struct.Struct `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Timestamp when the message was created.
	Timestamp *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Type of payload to help consumers interpret the data correctly.
	// Examples: "xdr", "json", "avro", "protobuf", "raw"
	PayloadType string `protobuf:"bytes,4,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	// Unique identifier for the message.
	MessageId string `protobuf:"bytes,5,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Identifier for the source producing this message.
	SourceId string `protobuf:"bytes,6,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	// Sequence information to help with ordering and deduplication.
	SequenceNumber int64 `protobuf:"varint,7,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DataMessage) Reset() {
	*x = DataMessage{}
	mi := &file_proto_source_source_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataMessage) ProtoMessage() {}

func (x *DataMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_source_source_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataMessage.ProtoReflect.Descriptor instead.
func (*DataMessage) Descriptor() ([]byte, []int) {
	return file_proto_source_source_proto_rawDescGZIP(), []int{0}
}

func (x *DataMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DataMessage) GetMetadata() *_struct.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DataMessage) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DataMessage) GetPayloadType() string {
	if x != nil {
		return x.PayloadType
	}
	return ""
}

func (x *DataMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DataMessage) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *DataMessage) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

// Enhanced capabilities response with more detailed information.
type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_proto_source_source_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_source_source_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_source_source_proto_rawDescGZIP(), []int{1}
}

type CapabilitiesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Basic service information
	ServiceName       string   `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceVersion    string   `protobuf:"bytes,2,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"`
	SupportedFeatures []string `protobuf:"bytes,3,rep,name=supported_features,json=supportedFeatures,proto3" json:"supported_features,omitempty"`
	// Additional capabilities as structured data
	Capabilities *_struct.Struct `protobuf:"bytes,4,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Supported payload types this source can produce
	SupportedPayloadTypes []string `protobuf:"bytes,5,rep,name=supported_payload_types,json=supportedPayloadTypes,proto3" json:"supported_payload_types,omitempty"`
	// Configuration schema - can be used by clients to validate config
	ConfigSchema  *_struct.Struct `protobuf:"bytes,6,opt,name=config_schema,json=configSchema,proto3" json:"config_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_proto_source_source_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_source_source_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_source_source_proto_rawDescGZIP(), []int{2}
}

func (x *CapabilitiesResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *CapabilitiesResponse) GetServiceVersion() string {
	if x != nil {
		return x.ServiceVersion
	}
	return ""
}

func (x *CapabilitiesResponse) GetSupportedFeatures() []string {
	if x != nil {
		return x.SupportedFeatures
	}
	return nil
}

func (x *CapabilitiesResponse) GetCapabilities() *_struct.Struct {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *CapabilitiesResponse) GetSupportedPayloadTypes() []string {
	if x != nil {
		return x.SupportedPayloadTypes
	}
	return nil
}

func (x *CapabilitiesResponse) GetConfigSchema() *_struct.Struct {
	if x != nil {
		return x.ConfigSchema
	}
	return nil
}

// Enhanced configuration with structured data.
type ConfigureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Configuration as structured data instead of flat key-value pairs
	Config         *_struct.Struct                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	ValidationMode ConfigureRequest_ValidationMode `protobuf:"varint,2,opt,name=validation_mode,json=validationMode,proto3,enum=source.ConfigureRequest_ValidationMode" json:"validation_mode,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_proto_source_source_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_source_source_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_proto_source_source_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigureRequest) GetConfig() *_struct.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ConfigureRequest) GetValidationMode() ConfigureRequest_ValidationMode {
	if x != nil {
		return x.ValidationMode
	}
	return ConfigureRequest_VALIDATE_AND_APPLY
}

type ConfigureResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Success      bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Validation results if requested
	ValidationIssues []*ValidationIssue `protobuf:"bytes,3,rep,name=validation_issues,json=validationIssues,proto3" json:"validation_issues,omitempty"`
	// Current configuration after applying changes
	CurrentConfig *_struct.Struct `protobuf:"bytes,4,opt,name=current_config,json=currentConfig,proto3" json:"current_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_proto_source_source_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_source_source_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_proto_source_source_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigureResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ConfigureResponse) GetValidationIssues() []*ValidationIssue {
	if x != nil {
		return x.ValidationIssues
	}
	return nil
}

func (x *ConfigureResponse) GetCurrentConfig() *_struct.Struct {
	if x != nil {
		return x.CurrentConfig
	}
	return nil
}

// Validation issue details for configuration
type ValidationIssue struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Severity      ValidationIssue_Severity `protobuf:"varint,1,opt,name=severity,proto3,enum=source.ValidationIssue_Severity" json:"severity,omitempty"`
	Field         string                   `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Message       string                   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationIssue) Reset() {
	*x = ValidationIssue{}
	mi := &file_proto_source_source_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationIssue) ProtoMessage() {}

func (x *ValidationIssue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_source_source_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationIssue.ProtoReflect.Descriptor instead.
func (*ValidationIssue) Descriptor() ([]byte, []int) {
	return file_proto_source_source_proto_rawDescGZIP(), []int{5}
}

func (x *ValidationIssue) GetSeverity() ValidationIssue_Severity {
	if x != nil {
		return x.Severity
	}
	return ValidationIssue_ERROR
}

func (x *ValidationIssue) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidationIssue) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Enhanced start request with pagination and state options.
type StartRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional parameters as structured data
	Parameters *_struct.Struct `protobuf:"bytes,1,opt,name=parameters,proto3" json:"parameters,omitempty"`
	// Pagination and batching options
	Pagination *PaginationOptions `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Whether to resume from the last saved state
	ResumeFromLastState bool `protobuf:"varint,3,opt,name=resume_from_last_state,json=resumeFromLastState,proto3" json:"resume_from_last_state,omitempty"`
	// Filter criteria to apply when streaming data
	Filters       *_struct.Struct `protobuf:"bytes,4,opt,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_proto_source_source_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_source_source_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_proto_source_source_proto_rawDescGZIP(), []int{6}
}

func (x *StartRequest) GetParameters() *_struct.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *StartRequest) GetPagination() *PaginationOptions {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *StartRequest) GetResumeFromLastState() bool {
	if x != nil {
		return x.ResumeFromLastState
	}
	return false
}

func (x *StartRequest) GetFilters() *_struct.Struct {
	if x != nil {
		return x.Filters
	}
	return nil
}

type PaginationOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of items to fetch in a batch
	BatchSize int32 `protobuf:"varint,1,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	// Opaque token for continuing a previous request
	ContinuationToken string `protobuf:"bytes,2,opt,name=continuation_token,json=continuationToken,proto3" json:"continuation_token,omitempty"`
	// Maximum time to wait for a full batch (in seconds)
	MaxWaitTime   float64 `protobuf:"fixed64,3,opt,name=max_wait_time,json=maxWaitTime,proto3" json:"max_wait_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationOptions) Reset() {
	*x = PaginationOptions{}
	mi := &file_proto_source_source_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationOptions) ProtoMessage() {}

func (x *PaginationOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_source_source_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationOptions.ProtoReflect.Descriptor instead.
func (*PaginationOptions) Descriptor() ([]byte, []int) {
	return file_proto_source_source_proto_rawDescGZIP(), []int{7}
}

func (x *PaginationOptions) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *PaginationOptions) GetContinuationToken() string {
	if x != nil {
		return x.ContinuationToken
	}
	return ""
}

func (x *PaginationOptions) GetMaxWaitTime() float64 {
	if x != nil {
		return x.MaxWaitTime
	}
	return 0
}

type StartResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Success      bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Information about the started stream
	StreamId string `protobuf:"bytes,3,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	// Initial state information
	InitialState  *_struct.Struct `protobuf:"bytes,4,opt,name=initial_state,json=initialState,proto3" json:"initial_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_proto_source_source_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_source_source_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_proto_source_source_proto_rawDescGZIP(), []int{8}
}

func (x *StartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StartResponse) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *StartResponse) GetInitialState() *_struct.Struct {
	if x != nil {
		return x.InitialState
	}
	return nil
}

// Stop request with options
type StopRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: Specific stream ID to stop (if multiple streams exist)
	StreamId string `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	// Whether to save the current state before stopping
	SaveState     bool `protobuf:"varint,2,opt,name=save_state,json=saveState,proto3" json:"save_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_proto_source_source_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_source_source_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_proto_source_source_proto_rawDescGZIP(), []int{9}
}

func (x *StopRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *StopRequest) GetSaveState() bool {
	if x != nil {
		return x.SaveState
	}
	return false
}

type StopResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Success      bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Final state when stopping (if requested)
	FinalState    *_struct.Struct `protobuf:"bytes,3,opt,name=final_state,json=finalState,proto3" json:"final_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_proto_source_source_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_source_source_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_proto_source_source_proto_rawDescGZIP(), []int{10}
}

func (x *StopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StopResponse) GetFinalState() *_struct.Struct {
	if x != nil {
		return x.FinalState
	}
	return nil
}

// State management for resumable operations
type GetStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: State key or namespace
	StateKey      string `protobuf:"bytes,1,opt,name=state_key,json=stateKey,proto3" json:"state_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_proto_source_source_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_source_source_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_source_source_proto_rawDescGZIP(), []int{11}
}

func (x *GetStateRequest) GetStateKey() string {
	if x != nil {
		return x.StateKey
	}
	return ""
}

type GetStateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// State data as structured information
	State *_struct.Struct `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	// Last update timestamp
	LastUpdated   *timestamp.Timestamp `protobuf:"bytes,2,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateResponse) Reset() {
	*x = GetStateResponse{}
	mi := &file_proto_source_source_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateResponse) ProtoMessage() {}

func (x *GetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_source_source_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateResponse.ProtoReflect.Descriptor instead.
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_source_source_proto_rawDescGZIP(), []int{12}
}

func (x *GetStateResponse) GetState() *_struct.Struct {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *GetStateResponse) GetLastUpdated() *timestamp.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

type SetStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// State data to store
	State *_struct.Struct `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	// Optional: State key or namespace
	StateKey      string `protobuf:"bytes,2,opt,name=state_key,json=stateKey,proto3" json:"state_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStateRequest) Reset() {
	*x = SetStateRequest{}
	mi := &file_proto_source_source_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStateRequest) ProtoMessage() {}

func (x *SetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_source_source_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStateRequest.ProtoReflect.Descriptor instead.
func (*SetStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_source_source_proto_rawDescGZIP(), []int{13}
}

func (x *SetStateRequest) GetState() *_struct.Struct {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *SetStateRequest) GetStateKey() string {
	if x != nil {
		return x.StateKey
	}
	return ""
}

type SetStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStateResponse) Reset() {
	*x = SetStateResponse{}
	mi := &file_proto_source_source_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStateResponse) ProtoMessage() {}

func (x *SetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_source_source_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStateResponse.ProtoReflect.Descriptor instead.
func (*SetStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_source_source_proto_rawDescGZIP(), []int{14}
}

func (x *SetStateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetStateResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Health check for monitoring
type HealthCheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional detailed check type
	Detailed      bool `protobuf:"varint,1,opt,name=detailed,proto3" json:"detailed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_source_source_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_source_source_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_source_source_proto_rawDescGZIP(), []int{15}
}

func (x *HealthCheckRequest) GetDetailed() bool {
	if x != nil {
		return x.Detailed
	}
	return false
}

type HealthCheckResponse struct {
	state  protoimpl.MessageState            `protogen:"open.v1"`
	Status HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=source.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	// Detailed component health states
	Components []*ComponentHealth `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"`
	// Current processing metrics
	Metrics       *_struct.Struct `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_source_source_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_source_source_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_source_source_proto_rawDescGZIP(), []int{16}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *HealthCheckResponse) GetComponents() []*ComponentHealth {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *HealthCheckResponse) GetMetrics() *_struct.Struct {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type ComponentHealth struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	ComponentName string                            `protobuf:"bytes,1,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,2,opt,name=status,proto3,enum=source.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	Message       string                            `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentHealth) Reset() {
	*x = ComponentHealth{}
	mi := &file_proto_source_source_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentHealth) ProtoMessage() {}

func (x *ComponentHealth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_source_source_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentHealth.ProtoReflect.Descriptor instead.
func (*ComponentHealth) Descriptor() ([]byte, []int) {
	return file_proto_source_source_proto_rawDescGZIP(), []int{17}
}

func (x *ComponentHealth) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *ComponentHealth) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *ComponentHealth) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Source data snapshot - retrieve specific data points
type SnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier(s) for the data to snapshot
	Identifiers []string `protobuf:"bytes,1,rep,name=identifiers,proto3" json:"identifiers,omitempty"`
	// Whether to include metadata
	IncludeMetadata bool `protobuf:"varint,2,opt,name=include_metadata,json=includeMetadata,proto3" json:"include_metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_proto_source_source_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_source_source_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_source_source_proto_rawDescGZIP(), []int{18}
}

func (x *SnapshotRequest) GetIdentifiers() []string {
	if x != nil {
		return x.Identifiers
	}
	return nil
}

func (x *SnapshotRequest) GetIncludeMetadata() bool {
	if x != nil {
		return x.IncludeMetadata
	}
	return false
}

type SnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*DataMessage         `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_proto_source_source_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_source_source_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_source_source_proto_rawDescGZIP(), []int{19}
}

func (x *SnapshotResponse) GetSnapshots() []*DataMessage {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

// Commands that can be sent during interactive streaming
type StreamCommand struct {
	state       protoimpl.MessageState    `protogen:"open.v1"`
	CommandType StreamCommand_CommandType `protobuf:"varint,1,opt,name=command_type,json=commandType,proto3,enum=source.StreamCommand_CommandType" json:"command_type,omitempty"`
	// Command parameters
	Parameters *_struct.Struct `protobuf:"bytes,2,opt,name=parameters,proto3" json:"parameters,omitempty"`
	// Correlation ID for matching commands with responses
	CorrelationId string `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamCommand) Reset() {
	*x = StreamCommand{}
	mi := &file_proto_source_source_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCommand) ProtoMessage() {}

func (x *StreamCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_source_source_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCommand.ProtoReflect.Descriptor instead.
func (*StreamCommand) Descriptor() ([]byte, []int) {
	return file_proto_source_source_proto_rawDescGZIP(), []int{20}
}

func (x *StreamCommand) GetCommandType() StreamCommand_CommandType {
	if x != nil {
		return x.CommandType
	}
	return StreamCommand_PAUSE
}

func (x *StreamCommand) GetParameters() *_struct.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *StreamCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

var File_proto_source_source_proto protoreflect.FileDescriptor

const file_proto_source_source_proto_rawDesc = "" +
	"\n" +
	"\x19proto/source/source.proto\x12\x06source\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x9e\x02\n" +
	"\vDataMessage\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x123\n" +
	"\bmetadata\x18\x02 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12!\n" +
	"\fpayload_type\x18\x04 \x01(\tR\vpayloadType\x12\x1d\n" +
	"\n" +
	"message_id\x18\x05 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsource_id\x18\x06 \x01(\tR\bsourceId\x12'\n" +
	"\x0fsequence_number\x18\a \x01(\x03R\x0esequenceNumber\"\x15\n" +
	"\x13CapabilitiesRequest\"\xc4\x02\n" +
	"\x14CapabilitiesResponse\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12'\n" +
	"\x0fservice_version\x18\x02 \x01(\tR\x0eserviceVersion\x12-\n" +
	"\x12supported_features\x18\x03 \x03(\tR\x11supportedFeatures\x12;\n" +
	"\fcapabilities\x18\x04 \x01(\v2\x17.google.protobuf.StructR\fcapabilities\x126\n" +
	"\x17supported_payload_types\x18\x05 \x03(\tR\x15supportedPayloadTypes\x12<\n" +
	"\rconfig_schema\x18\x06 \x01(\v2\x17.google.protobuf.StructR\fconfigSchema\"\xd2\x01\n" +
	"\x10ConfigureRequest\x12/\n" +
	"\x06config\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06config\x12P\n" +
	"\x0fvalidation_mode\x18\x02 \x01(\x0e2'.source.ConfigureRequest.ValidationModeR\x0evalidationMode\";\n" +
	"\x0eValidationMode\x12\x16\n" +
	"\x12VALIDATE_AND_APPLY\x10\x00\x12\x11\n" +
	"\rVALIDATE_ONLY\x10\x01\"\xd8\x01\n" +
	"\x11ConfigureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12D\n" +
	"\x11validation_issues\x18\x03 \x03(\v2\x17.source.ValidationIssueR\x10validationIssues\x12>\n" +
	"\x0ecurrent_config\x18\x04 \x01(\v2\x17.google.protobuf.StructR\rcurrentConfig\"\xad\x01\n" +
	"\x0fValidationIssue\x12<\n" +
	"\bseverity\x18\x01 \x01(\x0e2 .source.ValidationIssue.SeverityR\bseverity\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\",\n" +
	"\bSeverity\x12\t\n" +
	"\x05ERROR\x10\x00\x12\v\n" +
	"\aWARNING\x10\x01\x12\b\n" +
	"\x04INFO\x10\x02\"\xea\x01\n" +
	"\fStartRequest\x127\n" +
	"\n" +
	"parameters\x18\x01 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\x129\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.source.PaginationOptionsR\n" +
	"pagination\x123\n" +
	"\x16resume_from_last_state\x18\x03 \x01(\bR\x13resumeFromLastState\x121\n" +
	"\afilters\x18\x04 \x01(\v2\x17.google.protobuf.StructR\afilters\"\x85\x01\n" +
	"\x11PaginationOptions\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x01 \x01(\x05R\tbatchSize\x12-\n" +
	"\x12continuation_token\x18\x02 \x01(\tR\x11continuationToken\x12\"\n" +
	"\rmax_wait_time\x18\x03 \x01(\x01R\vmaxWaitTime\"\xa9\x01\n" +
	"\rStartResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1b\n" +
	"\tstream_id\x18\x03 \x01(\tR\bstreamId\x12<\n" +
	"\rinitial_state\x18\x04 \x01(\v2\x17.google.protobuf.StructR\finitialState\"I\n" +
	"\vStopRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x1d\n" +
	"\n" +
	"save_state\x18\x02 \x01(\bR\tsaveState\"\x87\x01\n" +
	"\fStopResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x128\n" +
	"\vfinal_state\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"finalState\".\n" +
	"\x0fGetStateRequest\x12\x1b\n" +
	"\tstate_key\x18\x01 \x01(\tR\bstateKey\"\x80\x01\n" +
	"\x10GetStateResponse\x12-\n" +
	"\x05state\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x05state\x12=\n" +
	"\flast_updated\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\"]\n" +
	"\x0fSetStateRequest\x12-\n" +
	"\x05state\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x05state\x12\x1b\n" +
	"\tstate_key\x18\x02 \x01(\tR\bstateKey\"Q\n" +
	"\x10SetStateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"0\n" +
	"\x12HealthCheckRequest\x12\x1a\n" +
	"\bdetailed\x18\x01 \x01(\bR\bdetailed\"\xb1\x02\n" +
	"\x13HealthCheckResponse\x12A\n" +
	"\x06status\x18\x01 \x01(\x0e2).source.HealthCheckResponse.ServingStatusR\x06status\x127\n" +
	"\n" +
	"components\x18\x02 \x03(\v2\x17.source.ComponentHealthR\n" +
	"components\x121\n" +
	"\ametrics\x18\x03 \x01(\v2\x17.google.protobuf.StructR\ametrics\"k\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\x12\x13\n" +
	"\x0fSERVICE_UNKNOWN\x10\x03\x12\f\n" +
	"\bSTARTING\x10\x04\x12\f\n" +
	"\bSTOPPING\x10\x05\"\x95\x01\n" +
	"\x0fComponentHealth\x12%\n" +
	"\x0ecomponent_name\x18\x01 \x01(\tR\rcomponentName\x12A\n" +
	"\x06status\x18\x02 \x01(\x0e2).source.HealthCheckResponse.ServingStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"^\n" +
	"\x0fSnapshotRequest\x12 \n" +
	"\videntifiers\x18\x01 \x03(\tR\videntifiers\x12)\n" +
	"\x10include_metadata\x18\x02 \x01(\bR\x0fincludeMetadata\"E\n" +
	"\x10SnapshotResponse\x121\n" +
	"\tsnapshots\x18\x01 \x03(\v2\x13.source.DataMessageR\tsnapshots\"\x82\x02\n" +
	"\rStreamCommand\x12D\n" +
	"\fcommand_type\x18\x01 \x01(\x0e2!.source.StreamCommand.CommandTypeR\vcommandType\x127\n" +
	"\n" +
	"parameters\x18\x02 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\"K\n" +
	"\vCommandType\x12\t\n" +
	"\x05PAUSE\x10\x00\x12\n" +
	"\n" +
	"\x06RESUME\x10\x01\x12\n" +
	"\n" +
	"\x06FILTER\x10\x02\x12\b\n" +
	"\x04SEEK\x10\x03\x12\x0f\n" +
	"\vACKNOWLEDGE\x10\x042\xea\x04\n" +
	"\rSourceService\x12L\n" +
	"\x0fGetCapabilities\x12\x1b.source.CapabilitiesRequest\x1a\x1c.source.CapabilitiesResponse\x12@\n" +
	"\tConfigure\x12\x18.source.ConfigureRequest\x1a\x19.source.ConfigureResponse\x12=\n" +
	"\x0eStartStreaming\x12\x14.source.StartRequest\x1a\x13.source.DataMessage0\x01\x12:\n" +
	"\rStopStreaming\x12\x13.source.StopRequest\x1a\x14.source.StopResponse\x12=\n" +
	"\bGetState\x12\x17.source.GetStateRequest\x1a\x18.source.GetStateResponse\x12=\n" +
	"\bSetState\x12\x17.source.SetStateRequest\x1a\x18.source.SetStateResponse\x12F\n" +
	"\vCheckHealth\x12\x1a.source.HealthCheckRequest\x1a\x1b.source.HealthCheckResponse\x12@\n" +
	"\vGetSnapshot\x12\x17.source.SnapshotRequest\x1a\x18.source.SnapshotResponse\x12F\n" +
	"\x14InteractiveStreaming\x12\x15.source.StreamCommand\x1a\x13.source.DataMessage(\x010\x01B/Z-github.com/withObsrvr/flow-proto/proto/sourceb\x06proto3"

var (
	file_proto_source_source_proto_rawDescOnce sync.Once
	file_proto_source_source_proto_rawDescData []byte
)

func file_proto_source_source_proto_rawDescGZIP() []byte {
	file_proto_source_source_proto_rawDescOnce.Do(func() {
		file_proto_source_source_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_source_source_proto_rawDesc), len(file_proto_source_source_proto_rawDesc)))
	})
	return file_proto_source_source_proto_rawDescData
}

var file_proto_source_source_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_source_source_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_source_source_proto_goTypes = []any{
	(ConfigureRequest_ValidationMode)(0),   // 0: source.ConfigureRequest.ValidationMode
	(ValidationIssue_Severity)(0),          // 1: source.ValidationIssue.Severity
	(HealthCheckResponse_ServingStatus)(0), // 2: source.HealthCheckResponse.ServingStatus
	(StreamCommand_CommandType)(0),         // 3: source.StreamCommand.CommandType
	(*DataMessage)(nil),                    // 4: source.DataMessage
	(*CapabilitiesRequest)(nil),            // 5: source.CapabilitiesRequest
	(*CapabilitiesResponse)(nil),           // 6: source.CapabilitiesResponse
	(*ConfigureRequest)(nil),               // 7: source.ConfigureRequest
	(*ConfigureResponse)(nil),              // 8: source.ConfigureResponse
	(*ValidationIssue)(nil),                // 9: source.ValidationIssue
	(*StartRequest)(nil),                   // 10: source.StartRequest
	(*PaginationOptions)(nil),              // 11: source.PaginationOptions
	(*StartResponse)(nil),                  // 12: source.StartResponse
	(*StopRequest)(nil),                    // 13: source.StopRequest
	(*StopResponse)(nil),                   // 14: source.StopResponse
	(*GetStateRequest)(nil),                // 15: source.GetStateRequest
	(*GetStateResponse)(nil),               // 16: source.GetStateResponse
	(*SetStateRequest)(nil),                // 17: source.SetStateRequest
	(*SetStateResponse)(nil),               // 18: source.SetStateResponse
	(*HealthCheckRequest)(nil),             // 19: source.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 20: source.HealthCheckResponse
	(*ComponentHealth)(nil),                // 21: source.ComponentHealth
	(*SnapshotRequest)(nil),                // 22: source.SnapshotRequest
	(*SnapshotResponse)(nil),               // 23: source.SnapshotResponse
	(*StreamCommand)(nil),                  // 24: source.StreamCommand
	(*_struct.Struct)(nil),                 // 25: google.protobuf.Struct
	(*timestamp.Timestamp)(nil),            // 26: google.protobuf.Timestamp
}
var file_proto_source_source_proto_depIdxs = []int32{
	25, // 0: source.DataMessage.metadata:type_name -> google.protobuf.Struct
	26, // 1: source.DataMessage.timestamp:type_name -> google.protobuf.Timestamp
	25, // 2: source.CapabilitiesResponse.capabilities:type_name -> google.protobuf.Struct
	25, // 3: source.CapabilitiesResponse.config_schema:type_name -> google.protobuf.Struct
	25, // 4: source.ConfigureRequest.config:type_name -> google.protobuf.Struct
	0,  // 5: source.ConfigureRequest.validation_mode:type_name -> source.ConfigureRequest.ValidationMode
	9,  // 6: source.ConfigureResponse.validation_issues:type_name -> source.ValidationIssue
	25, // 7: source.ConfigureResponse.current_config:type_name -> google.protobuf.Struct
	1,  // 8: source.ValidationIssue.severity:type_name -> source.ValidationIssue.Severity
	25, // 9: source.StartRequest.parameters:type_name -> google.protobuf.Struct
	11, // 10: source.StartRequest.pagination:type_name -> source.PaginationOptions
	25, // 11: source.StartRequest.filters:type_name -> google.protobuf.Struct
	25, // 12: source.StartResponse.initial_state:type_name -> google.protobuf.Struct
	25, // 13: source.StopResponse.final_state:type_name -> google.protobuf.Struct
	25, // 14: source.GetStateResponse.state:type_name -> google.protobuf.Struct
	26, // 15: source.GetStateResponse.last_updated:type_name -> google.protobuf.Timestamp
	25, // 16: source.SetStateRequest.state:type_name -> google.protobuf.Struct
	2,  // 17: source.HealthCheckResponse.status:type_name -> source.HealthCheckResponse.ServingStatus
	21, // 18: source.HealthCheckResponse.components:type_name -> source.ComponentHealth
	25, // 19: source.HealthCheckResponse.metrics:type_name -> google.protobuf.Struct
	2,  // 20: source.ComponentHealth.status:type_name -> source.HealthCheckResponse.ServingStatus
	4,  // 21: source.SnapshotResponse.snapshots:type_name -> source.DataMessage
	3,  // 22: source.StreamCommand.command_type:type_name -> source.StreamCommand.CommandType
	25, // 23: source.StreamCommand.parameters:type_name -> google.protobuf.Struct
	5,  // 24: source.SourceService.GetCapabilities:input_type -> source.CapabilitiesRequest
	7,  // 25: source.SourceService.Configure:input_type -> source.ConfigureRequest
	10, // 26: source.SourceService.StartStreaming:input_type -> source.StartRequest
	13, // 27: source.SourceService.StopStreaming:input_type -> source.StopRequest
	15, // 28: source.SourceService.GetState:input_type -> source.GetStateRequest
	17, // 29: source.SourceService.SetState:input_type -> source.SetStateRequest
	19, // 30: source.SourceService.CheckHealth:input_type -> source.HealthCheckRequest
	22, // 31: source.SourceService.GetSnapshot:input_type -> source.SnapshotRequest
	24, // 32: source.SourceService.InteractiveStreaming:input_type -> source.StreamCommand
	6,  // 33: source.SourceService.GetCapabilities:output_type -> source.CapabilitiesResponse
	8,  // 34: source.SourceService.Configure:output_type -> source.ConfigureResponse
	4,  // 35: source.SourceService.StartStreaming:output_type -> source.DataMessage
	14, // 36: source.SourceService.StopStreaming:output_type -> source.StopResponse
	16, // 37: source.SourceService.GetState:output_type -> source.GetStateResponse
	18, // 38: source.SourceService.SetState:output_type -> source.SetStateResponse
	20, // 39: source.SourceService.CheckHealth:output_type -> source.HealthCheckResponse
	23, // 40: source.SourceService.GetSnapshot:output_type -> source.SnapshotResponse
	4,  // 41: source.SourceService.InteractiveStreaming:output_type -> source.DataMessage
	33, // [33:42] is the sub-list for method output_type
	24, // [24:33] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_proto_source_source_proto_init() }
func file_proto_source_source_proto_init() {
	if File_proto_source_source_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_source_source_proto_rawDesc), len(file_proto_source_source_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_source_source_proto_goTypes,
		DependencyIndexes: file_proto_source_source_proto_depIdxs,
		EnumInfos:         file_proto_source_source_proto_enumTypes,
		MessageInfos:      file_proto_source_source_proto_msgTypes,
	}.Build()
	File_proto_source_source_proto = out.File
	file_proto_source_source_proto_goTypes = nil
	file_proto_source_source_proto_depIdxs = nil
}
